### ISSUE TITLE
Contracts- SYLLABUS / ENROLLMENTS Page

### ISSUE THREAD

**Issue by skwatters** [TinyALE/tiny-ale#94]
SYLLABUS
**DONE** Add a Schedule heading to the syllabus info with a drop down that is tied to the set Class periods (under Settings) this field should also populate on the Student Learning Plan page - creating a student schedule / enrollments. https://github.com/TinyALE/tiny-ale/issues/96

**DONE** The Credits field can live on this page or on the Enrollments page but should always "talk to each other" additions/updates/deletes should happen in both places simultaneously.

**DONE** Currently Credits are added using the Default Credits box on the Enrollment page - this also has the option of assigning the Credit to active enrollments. *The syllabus page should be read-only. Add the mass-update option provided in the current product, on enrollments*

**DONE** Would prefer that the option to add credit via the Syllabus page be deleted and remain on the Enrollments page. The chosen Default Credit will appear on the Syllabus page based on what is entered on the Enrollments page.

                      Default Credits  - Change defaults Assign to active enrollments
                      SS - American Government & Economics (HSS1742) / 0.5

**DONE** The Credits field has a + to add also need the ability to change/delete same would apply to the Default Credit on the Enrollments page - need the ability to change/delete. *need to be able to delete a credit in the credits editor* 

**DONE** -Learning Requirements - chose Edit and clicked a box, wouldn't SAVE, was able to Cancel. *it's crashing, investigate*

 ENROLLMENTS
**DONE** When adding enrollees- please add the entire ACTIVE list as a dropdown with check boxes so that more than one student may be added at a time. *display Lastname, Firstname (Nickname) (Pronoun if present) for results and tiles*
**DONE** Add Note feature opens a type in the box but doesn't SAVE - if its the first note being added.
**DONE** Added a note to a student with a prior note and it saved it over the top of the first one.
**DONE** Note Writer should be able to delete their own notes
**DONE** Admin should be able to delete any notes.

-Under the Credit Assignments Column;
**DONE** -When a student has been Fulfilled there should be no option to add/change/delete the credit assignment from this page. 
-When a student has been Canceled there should be no option to add/change/delete the credit assigned until the enrollment has been Reinstated to Active.
-When clicking on a current course/credit assignment to update the amount of credit or to change the course name assigned please add the current course list to the Course dialog box - the current course could be highlighted - as it is now.

@skwatters is this ok for showing the current course? 
![Screenshot from 2021-09-02 10-44-44](https://user-images.githubusercontent.com/11142/131891955-07c8704d-899d-4713-9067-62a26529935d.png)

**DONE** *The current course list should appear anywhere a course is being chosen. *verify that inactive credits are not selectable in the credits finder*

* ensure that Course Codes that have no active or fulfilled enrollments can be deleted

**Comment by artzte** [comment]
have addressed all these issues
